### ISSUE TITLE
FEDERATED_ACCESS_TOKEN_RESPONSE not SET

### ISSUE THREAD

**Issue by Sp4m4** [ansforge/keycloak-prosanteconnect#13]
En passant par votre connecteur keycloak-prosanteconnect, nous rencontrons toujours le même soucis reporté lors d'une demande précédente.
L'erreur intervient au niveau de org.keycloak.broker.oidc.OIDCIdentityProvider.authenticationFinished(OIDCIdentityProvider.java:642) où keycloak attend FEDERATED_ACCESS_TOKEN_RESPONSE qui n'est pas set.
Dans le code du connecteur PSC, fichier ProSanteConnectIdentityProvider.java ligne 371, si le token et le session state ne sont pas nul, alors FEDERATED_ACCESS_TOKEN_RESPONSE n'est pas set dans le context ce qui conduit dans notre cas à l'erreur décrite.
S'agit-il d'un problème de configuration et si oui auriez-vous une idée de son origine s'il vous plait?
Nous avons patché le repo keycloak-prosanteconnect en local en attendant pour pouvoir avancer sur nos développements.

**Comment by MJUi** [comment]
L'anomalie remontée devrait avoir été corrigée avec la dernière release.
