### ISSUE TITLE
Error when using PSC theme

### ISSUE THREAD

**Issue by cpanissod** [ansforge/keycloak-prosanteconnect#15]
Keycloak 22.0.5
Provider PSC 3.0.0
---
Error HTTP 500
keycloak-1  | 2023-11-22 09:21:12,015 ERROR [org.keycloak.forms.login.freemarker.FreeMarkerLoginFormsProvider] (executor-thread-4) Failed to process template: org.keycloak.theme.FreeMarkerException: Failed to process template login.ftl
keycloak-health-checks-keycloak-1  |    at org.keycloak.theme.freemarker.DefaultFreeMarkerProvider.processTemplate(DefaultFreeMarkerProvider.java:52)

**Comment by kguilloux-gh** [comment]
Bonjour,
Pourriez vous détailler et préciser quelles ont été les actions qui ont généré l'erreur ?
Cordialement.

**Comment by kguilloux-gh** [comment]
Bonjour,
Merci pour toutes ces précisions.
Le sujet est pris en charge, on revient vers vous rapidement.
Cordialement.

**Comment by edegenetais-nx** [comment]
Pour information, le centrage du logo fait l'objet de l'issue #20
