### ISSUE TITLE
Compatibilité avec Keycloak 20

### ISSUE THREAD

**Issue by Polaris-Software** [ansforge/keycloak-prosanteconnect#6]
Bonjour, 

Je viens de récupérer le provider, l'installation n'a pas posée de problème en revanche, par rapport aux screenshots donnés en exemple (au-delà du changement d'UI de Keycloak) je ne retrouve pas ni le champs du choix d'environnement (BAS vs Prod) ni le choix du niveau eIDAS. 
![image](https://user-images.githubusercontent.com/90192468/229828800-245140a5-a1b4-4d07-bfd3-9c95c6c95355.png)

Les paramètres présents dans "General Settings" sont spécifiables à la création du provider, les "Advanced" deviennent dispo ensuite.

**Comment by Polaris-Software** [comment]
[EDIT]. Malgré les paramètres qui ne sont plus dans l'UI, l'authentification fonctionne côté eCPS, en revanche en retour, il semble que votre provider attende un claim ACR dans l'idToken qui est absent de la réponse. Par ailleurs quand je décode les tokens (demandés en scope_all) je suis loin de retrouver les champs présents sur l'appli TryeCPS.

**Comment by MJUi** [comment]
Bonjour,
Normalement, le problème lié à l'acr claim est résolu avec la release 2.0.2, à confirmer - le niveau Eidas1 est le seul niveau maintenant geré nativement par le connecteur.
Concernant le choix de l'environnement (bac à sable / production), voir la documentation README mises à jour - une variable système permet de passer de production à bac à sable.
