### ISSUE TITLE
Code pour construire keycloak-prosanteconnect-2.0.0.jar

### ISSUE THREAD

**Issue by fliot** [ansforge/keycloak-prosanteconnect#7]
Bonjour,
Toutes les branches du projet ont un pom permettant de construire
```
  <groupId>fr.ans.keycloak</groupId>
  <artifactId>keycloak-prosanteconnect</artifactId>
  <version>1.0.0</version>
```
Pourtant le readme parle de keycloak-prosanteconnect-**2.0.0** et en effet, les captures sont faites sur des version 21.x.xx de Keycloak.

A quel endroit se trouve le le code permettant de fabriquer keycloak-prosanteconnect-**2.0.0** ?

Merci d'avance,
Bien cordialement.

**Comment by MJUi** [comment]
Bonjour,

Le code source et la release ont bien été mises à jour pour la version 21.0.X de Keycloak.

Cordialement.
